package pracenjenaucnihkonferencija;


/**
* pracenjenaucnihkonferencija/_NaucneKonferencijeStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public class _NaucneKonferencijeStub extends org.omg.CORBA.portable.ObjectImpl implements pracenjenaucnihkonferencija.NaucneKonferencije
{

  public boolean dodavanjeRada (pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad rad)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("dodavanjeRada", true);
                pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.write ($out, rad);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return dodavanjeRada (rad        );
            } finally {
                _releaseReply ($in);
            }
  } // dodavanjeRada

  public pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi pregledRadova ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pregledRadova", true);
                $in = _invoke ($out);
                pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi $result = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadoviHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return pregledRadova (        );
            } finally {
                _releaseReply ($in);
            }
  } // pregledRadova

  public boolean uploadRada (pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload rad)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("uploadRada", true);
                pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUploadHelper.write ($out, rad);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return uploadRada (rad        );
            } finally {
                _releaseReply ($in);
            }
  } // uploadRada

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pracenjenaucnihkonferencija/NaucneKonferencije:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _NaucneKonferencijeStub
