package pracenjenaucnihkonferencija;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public interface NaucneKonferencijeOperations 
{
  boolean dodavanjeRada (pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad rad);
  pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi pregledRadova ();
  boolean uploadRada (pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload rad);
} // interface NaucneKonferencijeOperations
