package pracenjenaucnihkonferencija;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public abstract class NaucneKonferencijePOA extends org.omg.PortableServer.Servant
 implements pracenjenaucnihkonferencija.NaucneKonferencijeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("dodavanjeRada", new java.lang.Integer (0));
    _methods.put ("pregledRadova", new java.lang.Integer (1));
    _methods.put ("uploadRada", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // pracenjenaucnihkonferencija/NaucneKonferencije/dodavanjeRada
       {
         pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad rad = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.read (in);
         boolean $result = false;
         $result = this.dodavanjeRada (rad);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // pracenjenaucnihkonferencija/NaucneKonferencije/pregledRadova
       {
         pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi $result = null;
         $result = this.pregledRadova ();
         out = $rh.createReply();
         pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadoviHelper.write (out, $result);
         break;
       }

       case 2:  // pracenjenaucnihkonferencija/NaucneKonferencije/uploadRada
       {
         pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload rad = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUploadHelper.read (in);
         boolean $result = false;
         $result = this.uploadRada (rad);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pracenjenaucnihkonferencija/NaucneKonferencije:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NaucneKonferencije _this() 
  {
    return NaucneKonferencijeHelper.narrow(
    super._this_object());
  }

  public NaucneKonferencije _this(org.omg.CORBA.ORB orb) 
  {
    return NaucneKonferencijeHelper.narrow(
    super._this_object(orb));
  }


} // class NaucneKonferencijePOA
