package pracenjenaucnihkonferencija;


/**
* pracenjenaucnihkonferencija/NaucneKonferencije.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public interface NaucneKonferencije extends NaucneKonferencijeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NaucneKonferencije
