package Informator.ISPackage;


/**
* Informator/ISPackage/Korisnik.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IS.idl
* Tuesday, October 13, 2015 4:17:37 PM CEST
*/

public final class Korisnik implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  public Korisnik ()
  {
  } // ctor

  public Korisnik (String _id)
  {
    id = _id;
  } // ctor

} // class Korisnik
