package oglasi.AdvertismentPackage;


/**
* oglasi/AdvertismentPackage/Ads.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public final class Ads implements org.omg.CORBA.portable.IDLEntity
{
  public oglasi.AdvertismentPackage.Ad ads[] = null;

  public Ads ()
  {
  } // ctor

  public Ads (oglasi.AdvertismentPackage.Ad[] _ads)
  {
    ads = _ads;
  } // ctor

} // class Ads
