package oglasi.AdvertismentPackage;

/**
* oglasi/AdvertismentPackage/AdsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public final class AdsHolder implements org.omg.CORBA.portable.Streamable
{
  public oglasi.AdvertismentPackage.Ads value = null;

  public AdsHolder ()
  {
  }

  public AdsHolder (oglasi.AdvertismentPackage.Ads initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = oglasi.AdvertismentPackage.AdsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    oglasi.AdvertismentPackage.AdsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return oglasi.AdvertismentPackage.AdsHelper.type ();
  }

}
