package Informator;

/**
* Informator/ISHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IS.idl
* Tuesday, October 13, 2015 4:17:37 PM CEST
*/

public final class ISHolder implements org.omg.CORBA.portable.Streamable
{
  public Informator.IS value = null;

  public ISHolder ()
  {
  }

  public ISHolder (Informator.IS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Informator.ISHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Informator.ISHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Informator.ISHelper.type ();
  }

}
