package Informator;


/**
* Informator/ISOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IS.idl
* Tuesday, October 13, 2015 4:17:37 PM CEST
*/

public interface ISOperations 
{
  String prijava (Informator.ISPackage.Korisnik korisnik);
  Informator.ISPackage.Buffer repertoar ();
  String horoskop ();
  String loto ();
  String odjava (Informator.ISPackage.Korisnik korisnik);
} // interface ISOperations
