package calculator;

/**
* calculator/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Tuesday, April 20, 2010 3:48:01 PM CEST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public calculator.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (calculator.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator.CalculatorHelper.type ();
  }

}
