package calculator;


/**
* calculator/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Tuesday, April 20, 2010 3:48:01 PM CEST
*/

public interface CalculatorOperations 
{
  int add (int x, int y);
  int sub (int x, int y);
} // interface CalculatorOperations
