package pracenjenaucnihkonferencija.NaucneKonferencijePackage;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/Rad.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class Rad implements org.omg.CORBA.portable.IDLEntity
{
  public int idRada = (int)0;
  public String naziv = null;
  public String kratakSadrzaj = null;
  public int brojStranica = (int)0;

  public Rad ()
  {
  } // ctor

  public Rad (int _idRada, String _naziv, String _kratakSadrzaj, int _brojStranica)
  {
    idRada = _idRada;
    naziv = _naziv;
    kratakSadrzaj = _kratakSadrzaj;
    brojStranica = _brojStranica;
  } // ctor

} // class Rad
