package pracenjenaucnihkonferencija.NaucneKonferencijePackage;

/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/RadHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class RadHolder implements org.omg.CORBA.portable.Streamable
{
  public pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad value = null;

  public RadHolder ()
  {
  }

  public RadHolder (pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.type ();
  }

}
