package pracenjenaucnihkonferencija.NaucneKonferencijePackage;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/RadoviHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

abstract public class RadoviHelper
{
  private static String  _id = "IDL:pracenjenaucnihkonferencija/NaucneKonferencije/Radovi:1.0";

  public static void insert (org.omg.CORBA.Any a, pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "radovi",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadoviHelper.id (), "Radovi", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi read (org.omg.CORBA.portable.InputStream istream)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi value = new pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi ();
    int _len0 = istream.read_long ();
    value.radovi = new pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad[_len0];
    for (int _o1 = 0;_o1 < value.radovi.length; ++_o1)
      value.radovi[_o1] = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi value)
  {
    ostream.write_long (value.radovi.length);
    for (int _i0 = 0;_i0 < value.radovi.length; ++_i0)
      pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.write (ostream, value.radovi[_i0]);
  }

}
