package pracenjenaucnihkonferencija.NaucneKonferencijePackage;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/RadZaUpload.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class RadZaUpload implements org.omg.CORBA.portable.IDLEntity
{
  public byte sadrzaj[] = null;
  public String naziv = null;

  public RadZaUpload ()
  {
  } // ctor

  public RadZaUpload (byte[] _sadrzaj, String _naziv)
  {
    sadrzaj = _sadrzaj;
    naziv = _naziv;
  } // ctor

} // class RadZaUpload
