package pracenjenaucnihkonferencija.NaucneKonferencijePackage;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/RadHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

abstract public class RadHelper
{
  private static String  _id = "IDL:pracenjenaucnihkonferencija/NaucneKonferencije/Rad:1.0";

  public static void insert (org.omg.CORBA.Any a, pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "idRada",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "naziv",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "kratakSadrzaj",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "brojStranica",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadHelper.id (), "Rad", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad read (org.omg.CORBA.portable.InputStream istream)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad value = new pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad ();
    value.idRada = istream.read_long ();
    value.naziv = istream.read_string ();
    value.kratakSadrzaj = istream.read_string ();
    value.brojStranica = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad value)
  {
    ostream.write_long (value.idRada);
    ostream.write_string (value.naziv);
    ostream.write_string (value.kratakSadrzaj);
    ostream.write_long (value.brojStranica);
  }

}
