package pracenjenaucnihkonferencija.NaucneKonferencijePackage;

/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/RadoviHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class RadoviHolder implements org.omg.CORBA.portable.Streamable
{
  public pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi value = null;

  public RadoviHolder ()
  {
  }

  public RadoviHolder (pracenjenaucnihkonferencija.NaucneKonferencijePackage.Radovi initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadoviHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadoviHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadoviHelper.type ();
  }

}
