package pracenjenaucnihkonferencija.NaucneKonferencijePackage;

/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/RadZaUploadHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class RadZaUploadHolder implements org.omg.CORBA.portable.Streamable
{
  public pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload value = null;

  public RadZaUploadHolder ()
  {
  }

  public RadZaUploadHolder (pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUploadHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUploadHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUploadHelper.type ();
  }

}
