package pracenjenaucnihkonferencija.NaucneKonferencijePackage;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/RadZaUploadHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

abstract public class RadZaUploadHelper
{
  private static String  _id = "IDL:pracenjenaucnihkonferencija/NaucneKonferencije/RadZaUpload:1.0";

  public static void insert (org.omg.CORBA.Any a, pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "sadrzaj",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "naziv",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUploadHelper.id (), "RadZaUpload", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload read (org.omg.CORBA.portable.InputStream istream)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload value = new pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload ();
    int _len0 = istream.read_long ();
    value.sadrzaj = new byte[_len0];
    istream.read_octet_array (value.sadrzaj, 0, _len0);
    value.naziv = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pracenjenaucnihkonferencija.NaucneKonferencijePackage.RadZaUpload value)
  {
    ostream.write_long (value.sadrzaj.length);
    ostream.write_octet_array (value.sadrzaj, 0, value.sadrzaj.length);
    ostream.write_string (value.naziv);
  }

}
