package pracenjenaucnihkonferencija.NaucneKonferencijePackage;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/Ucesnik.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class Ucesnik implements org.omg.CORBA.portable.IDLEntity
{
  public String korisnickoIme = null;
  public String ime = null;
  public String prezime = null;

  public Ucesnik ()
  {
  } // ctor

  public Ucesnik (String _korisnickoIme, String _ime, String _prezime)
  {
    korisnickoIme = _korisnickoIme;
    ime = _ime;
    prezime = _prezime;
  } // ctor

} // class Ucesnik
