package oglasi;


/**
* oglasi/Advertisment.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public interface Advertisment extends AdvertismentOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Advertisment
