package oglasi;


/**
* oglasi/AdvertismentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public interface AdvertismentOperations 
{
  boolean createAd (String data);
  oglasi.AdvertismentPackage.Ads viewAll ();
  oglasi.AdvertismentPackage.Ad viewOne (oglasi.AdvertismentPackage.Ad ad);
} // interface AdvertismentOperations
