package pracenjenaucnihkonferencija.NaucneKonferencijePackage;


/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/Radovi.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class Radovi implements org.omg.CORBA.portable.IDLEntity
{
  public pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad radovi[] = null;

  public Radovi ()
  {
  } // ctor

  public Radovi (pracenjenaucnihkonferencija.NaucneKonferencijePackage.Rad[] _radovi)
  {
    radovi = _radovi;
  } // ctor

} // class Radovi
