package pracenjenaucnihkonferencija.NaucneKonferencijePackage;

/**
* pracenjenaucnihkonferencija/NaucneKonferencijePackage/UcesnikHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class UcesnikHolder implements org.omg.CORBA.portable.Streamable
{
  public pracenjenaucnihkonferencija.NaucneKonferencijePackage.Ucesnik value = null;

  public UcesnikHolder ()
  {
  }

  public UcesnikHolder (pracenjenaucnihkonferencija.NaucneKonferencijePackage.Ucesnik initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pracenjenaucnihkonferencija.NaucneKonferencijePackage.UcesnikHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijePackage.UcesnikHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pracenjenaucnihkonferencija.NaucneKonferencijePackage.UcesnikHelper.type ();
  }

}
