package oglasi.AdvertismentPackage;

/**
* oglasi/AdvertismentPackage/AdHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public final class AdHolder implements org.omg.CORBA.portable.Streamable
{
  public oglasi.AdvertismentPackage.Ad value = null;

  public AdHolder ()
  {
  }

  public AdHolder (oglasi.AdvertismentPackage.Ad initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = oglasi.AdvertismentPackage.AdHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    oglasi.AdvertismentPackage.AdHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return oglasi.AdvertismentPackage.AdHelper.type ();
  }

}
