package oglasi.AdvertismentPackage;


/**
* oglasi/AdvertismentPackage/Author.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public final class Author implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String surname = null;

  public Author ()
  {
  } // ctor

  public Author (String _name, String _surname)
  {
    name = _name;
    surname = _surname;
  } // ctor

} // class Author
