package oglasi.AdvertismentPackage;

/**
* oglasi/AdvertismentPackage/AuthorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public final class AuthorHolder implements org.omg.CORBA.portable.Streamable
{
  public oglasi.AdvertismentPackage.Author value = null;

  public AuthorHolder ()
  {
  }

  public AuthorHolder (oglasi.AdvertismentPackage.Author initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = oglasi.AdvertismentPackage.AuthorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    oglasi.AdvertismentPackage.AuthorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return oglasi.AdvertismentPackage.AuthorHelper.type ();
  }

}
