package oglasi.AdvertismentPackage;


/**
* oglasi/AdvertismentPackage/AdsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

abstract public class AdsHelper
{
  private static String  _id = "IDL:oglasi/Advertisment/Ads:1.0";

  public static void insert (org.omg.CORBA.Any a, oglasi.AdvertismentPackage.Ads that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static oglasi.AdvertismentPackage.Ads extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = oglasi.AdvertismentPackage.AdHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "ads",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (oglasi.AdvertismentPackage.AdsHelper.id (), "Ads", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static oglasi.AdvertismentPackage.Ads read (org.omg.CORBA.portable.InputStream istream)
  {
    oglasi.AdvertismentPackage.Ads value = new oglasi.AdvertismentPackage.Ads ();
    int _len0 = istream.read_long ();
    value.ads = new oglasi.AdvertismentPackage.Ad[_len0];
    for (int _o1 = 0;_o1 < value.ads.length; ++_o1)
      value.ads[_o1] = oglasi.AdvertismentPackage.AdHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, oglasi.AdvertismentPackage.Ads value)
  {
    ostream.write_long (value.ads.length);
    for (int _i0 = 0;_i0 < value.ads.length; ++_i0)
      oglasi.AdvertismentPackage.AdHelper.write (ostream, value.ads[_i0]);
  }

}
