package pracenjenaucnihkonferencija;

/**
* pracenjenaucnihkonferencija/NaucneKonferencijeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NaucneKonferencije.idl
* Sunday, May 18, 2014 12:26:59 PM CEST
*/

public final class NaucneKonferencijeHolder implements org.omg.CORBA.portable.Streamable
{
  public pracenjenaucnihkonferencija.NaucneKonferencije value = null;

  public NaucneKonferencijeHolder ()
  {
  }

  public NaucneKonferencijeHolder (pracenjenaucnihkonferencija.NaucneKonferencije initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pracenjenaucnihkonferencija.NaucneKonferencijeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pracenjenaucnihkonferencija.NaucneKonferencijeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pracenjenaucnihkonferencija.NaucneKonferencijeHelper.type ();
  }

}
