package Informator.ISPackage;

/**
* Informator/ISPackage/BufferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IS.idl
* Tuesday, October 13, 2015 4:17:37 PM CEST
*/

public final class BufferHolder implements org.omg.CORBA.portable.Streamable
{
  public Informator.ISPackage.Buffer value = null;

  public BufferHolder ()
  {
  }

  public BufferHolder (Informator.ISPackage.Buffer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Informator.ISPackage.BufferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Informator.ISPackage.BufferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Informator.ISPackage.BufferHelper.type ();
  }

}
