package Informator.ISPackage;

/**
* Informator/ISPackage/KorisnikHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IS.idl
* Tuesday, October 13, 2015 4:17:37 PM CEST
*/

public final class KorisnikHolder implements org.omg.CORBA.portable.Streamable
{
  public Informator.ISPackage.Korisnik value = null;

  public KorisnikHolder ()
  {
  }

  public KorisnikHolder (Informator.ISPackage.Korisnik initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Informator.ISPackage.KorisnikHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Informator.ISPackage.KorisnikHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Informator.ISPackage.KorisnikHelper.type ();
  }

}
