package Informator;


/**
* Informator/ISPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IS.idl
* Tuesday, October 13, 2015 4:17:37 PM CEST
*/

public abstract class ISPOA extends org.omg.PortableServer.Servant
 implements Informator.ISOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("prijava", new java.lang.Integer (0));
    _methods.put ("repertoar", new java.lang.Integer (1));
    _methods.put ("horoskop", new java.lang.Integer (2));
    _methods.put ("loto", new java.lang.Integer (3));
    _methods.put ("odjava", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Informator/IS/prijava
       {
         Informator.ISPackage.Korisnik korisnik = Informator.ISPackage.KorisnikHelper.read (in);
         String $result = null;
         $result = this.prijava (korisnik);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Informator/IS/repertoar
       {
         Informator.ISPackage.Buffer $result = null;
         $result = this.repertoar ();
         out = $rh.createReply();
         Informator.ISPackage.BufferHelper.write (out, $result);
         break;
       }

       case 2:  // Informator/IS/horoskop
       {
         String $result = null;
         $result = this.horoskop ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Informator/IS/loto
       {
         String $result = null;
         $result = this.loto ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // Informator/IS/odjava
       {
         Informator.ISPackage.Korisnik korisnik = Informator.ISPackage.KorisnikHelper.read (in);
         String $result = null;
         $result = this.odjava (korisnik);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Informator/IS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IS _this() 
  {
    return ISHelper.narrow(
    super._this_object());
  }

  public IS _this(org.omg.CORBA.ORB orb) 
  {
    return ISHelper.narrow(
    super._this_object(orb));
  }


} // class ISPOA
