package oglasi;


/**
* oglasi/AdvertismentPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public abstract class AdvertismentPOA extends org.omg.PortableServer.Servant
 implements oglasi.AdvertismentOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createAd", new java.lang.Integer (0));
    _methods.put ("viewAll", new java.lang.Integer (1));
    _methods.put ("viewOne", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // oglasi/Advertisment/createAd
       {
         String data = in.read_string ();
         boolean $result = false;
         $result = this.createAd (data);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // oglasi/Advertisment/viewAll
       {
         oglasi.AdvertismentPackage.Ads $result = null;
         $result = this.viewAll ();
         out = $rh.createReply();
         oglasi.AdvertismentPackage.AdsHelper.write (out, $result);
         break;
       }

       case 2:  // oglasi/Advertisment/viewOne
       {
         oglasi.AdvertismentPackage.Ad ad = oglasi.AdvertismentPackage.AdHelper.read (in);
         oglasi.AdvertismentPackage.Ad $result = null;
         $result = this.viewOne (ad);
         out = $rh.createReply();
         oglasi.AdvertismentPackage.AdHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:oglasi/Advertisment:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Advertisment _this() 
  {
    return AdvertismentHelper.narrow(
    super._this_object());
  }

  public Advertisment _this(org.omg.CORBA.ORB orb) 
  {
    return AdvertismentHelper.narrow(
    super._this_object(orb));
  }


} // class AdvertismentPOA
