package Informator.ISPackage;


/**
* Informator/ISPackage/Buffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IS.idl
* Tuesday, October 13, 2015 4:17:37 PM CEST
*/

public final class Buffer implements org.omg.CORBA.portable.IDLEntity
{
  public byte buffer[] = null;

  public Buffer ()
  {
  } // ctor

  public Buffer (byte[] _buffer)
  {
    buffer = _buffer;
  } // ctor

} // class Buffer
