package oglasi;

/**
* oglasi/AdvertismentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Advertisment.idl
* Thursday, October 1, 2015 8:01:04 PM CEST
*/

public final class AdvertismentHolder implements org.omg.CORBA.portable.Streamable
{
  public oglasi.Advertisment value = null;

  public AdvertismentHolder ()
  {
  }

  public AdvertismentHolder (oglasi.Advertisment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = oglasi.AdvertismentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    oglasi.AdvertismentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return oglasi.AdvertismentHelper.type ();
  }

}
